### ISSUE TITLE
[FEATURE] Introduce discovery movies section

### ISSUE THREAD

**Issue by perettijuan** [perettijuan/moviespreview#210]
## Tasks
- [x] Make genres UI code available to all application.
- [x] Introduce movie genres data layer infrastructure.
- [x] Add Use Cases for discover movie by genre feature.
- [x] Add discover movies with genre filters UI.
